import { useState } from 'react';

export const firmDomains: Record<number, string> = {
  1: 'ftmo.com',
  3: 'the5ers.com',
  4: 'fundednext.com',
  5: 'apextraderfunding.com',
  6: 'topstep.com',
  7: 'funderpro.com',
  8: 'trueforexfunds.com',
  9: 'earn2trade.com',
  10: 'instantfunding.com',
  11: 'fundingpips.com',
  12: 'alphacapitalgroup.uk',
  13: 'blueguardianfunding.com',
  14: 'e8markets.com',
  15: 'fxify.com',
  16: 'larkfunding.com',
  18: 'thetradingpit.com',
  19: 'goatfundedtrader.com',
  20: 'citytradersmperium.com',
  21: 'holaprime.com',
  23: 'audacitycapital.com',
  24: 'oneuptrader.com',
  25: 'bulenox.com',
  26: 'takeprofittrader.com',
  27: 'tradeday.com',
  30: 'myflashfunding.com',
  31: 'aquafunded.com',
  32: 'phoenixtrader.co',
  34: 'uprofit.com',
  35: 'thinkcapital.com',
  37: 'breakoutprop.com',
  41: 'maventrading.com',
  42: 'cryptofundtrader.com',
  43: 'bemfunding.com',
  44: 'toponetrader.com',
  45: 'qtfunded.com',
  46: 'fortraders.com',
  47: 'tradethepool.com',
  48: 'fundedelite.com',
  49: 'finotivefunding.com',
  50: 'monetafunded.com',
  51: 'atfunded.com',
  52: 'hantec.com',
  53: 'axi.com',
  54: 'nordicfunder.com',
  55: 'fundedtradingplus.com',
  56: 'fintokei.com',
  57: 'tradeify.com',
  58: 'myfundedfutures.com',
  59: 'alphafutures.io',
  60: 'lucidtrading.co',
  61: 'toponefutures.com',
  62: 'fundednext.com',
  63: 'traderslaunch.com',
  64: 'aquafunded.com',
  65: 'blueberryfunded.com',
  66: 'e8markets.com',
  67: 'futureselite.com',
  68: 'goatfundedtrader.com',
  69: 'yrmprop.com',
  70: 'sharkfunded.co',
  71: 'sfxfunded.com',
  72: 'fundedsquad.com',
  73: 'ftuk.com',
  74: 'propshoptrader.com',
  75: 'fundedfirm.com',
};

export const firmDomainsByName: Record<string, string> = {
  'FTMO': 'ftmo.com',
  'The 5%ers': 'the5ers.com',
  'Funded Next': 'fundednext.com',
  'Apex Trader': 'apextraderfunding.com',
  'TopStep': 'topstep.com',
  'Funder Pro': 'funderpro.com',
  'True Forex': 'trueforexfunds.com',
  'Earn2Trade': 'earn2trade.com',
  'Instant Funding': 'instantfunding.com',
  'FundingPips': 'fundingpips.com',
  'Alpha Capital': 'alphacapitalgroup.uk',
  'Blue Guardian': 'blueguardianfunding.com',
  'E8 Markets': 'e8markets.com',
  'FXIFY': 'fxify.com',
  'Lark Funding': 'larkfunding.com',
  'The Trading Pit': 'thetradingpit.com',
  'GoatFunded Trader': 'goatfundedtrader.com',
  'City Traders Imperium': 'citytradersmperium.com',
  'Hola Prime': 'holaprime.com',
  'Audacity Capital': 'audacitycapital.com',
  'OneUp Trader': 'oneuptrader.com',
  'Bulenox': 'bulenox.com',
  'Take Profit Trader': 'takeprofittrader.com',
  'TradeDay': 'tradeday.com',
  'My Flash Funding': 'myflashfunding.com',
  'AquaFunded': 'aquafunded.com',
  'Phoenix Trader': 'phoenixtrader.co',
  'Uprofit': 'uprofit.com',
  'ThinkCapital': 'thinkcapital.com',
  'Breakout Prop': 'breakoutprop.com',
  'Maven Trading': 'maventrading.com',
  'Crypto Fund Trader': 'cryptofundtrader.com',
  'BEM Funding': 'bemfunding.com',
  'Top One Trader': 'toponetrader.com',
  'QT Funded': 'qtfunded.com',
  'For Traders': 'fortraders.com',
  'Trade The Pool': 'tradethepool.com',
  'FundedElite': 'fundedelite.com',
  'Finotive Funding': 'finotivefunding.com',
  'Moneta Funded': 'monetafunded.com',
  'ATFunded': 'atfunded.com',
  'Hantec Trader': 'hantec.com',
  'Axi Select': 'axi.com',
  'Nordic Funder': 'nordicfunder.com',
  'Funded Trading Plus': 'fundedtradingplus.com',
  'Fintokei': 'fintokei.com',
  'Tradeify': 'tradeify.com',
  'My Funded Futures': 'myfundedfutures.com',
  'Alpha Futures': 'alphafutures.io',
  'Lucid Trading': 'lucidtrading.co',
  'Top One Futures': 'toponefutures.com',
  'FundedNext Futures': 'fundednext.com',
  'Traders Launch': 'traderslaunch.com',
  'AquaFutures': 'aquafunded.com',
  'Blueberry Futures': 'blueberryfunded.com',
  'E8 Futures': 'e8markets.com',
  'FuturesElite': 'futureselite.com',
  'Goat Funded Futures': 'goatfundedtrader.com',
  'YRM Prop': 'yrmprop.com',
  'SharkFunded': 'sharkfunded.co',
  'SFX Funded': 'sfxfunded.com',
  'FundedSquad': 'fundedsquad.com',
  'FTUK': 'ftuk.com',
  'PropShopTrader': 'propshoptrader.com',
  'FundedFirm': 'fundedfirm.com',
};

const localLogos: Record<number, string> = {
  1: '/logos/ftmo.png',
  3: '/logos/the5ers.png',
  4: '/logos/fundednext.png',
  5: '/logos/apex.png',
  6: '/logos/topstep.png',
  7: '/logos/funderpro.png',
  8: '/logos/trueforex.png',
  9: '/logos/earn2trade.png',
  10: '/logos/instantfunding.png',
  11: '/logos/fundingpips.png',
  12: '/logos/alphacapital.png',
  13: '/logos/blueguardian.png',
  14: '/logos/e8funding.png',
  15: '/logos/fxify.png',
  16: '/logos/larkfunding.png',
  18: '/logos/thetradingpit.png',
  19: '/logos/goatfunded.png',
  20: '/logos/citytradersmperium.png',
  21: '/logos/holaprime.png',
  23: '/logos/audacitycapital.png',
  24: '/logos/oneuptrader.png',
  25: '/logos/bulenox.png',
  26: '/logos/takeprofittrader.png',
  27: '/logos/tradeday.png',
  30: '/logos/myflashfunding.png',
  31: '/logos/aquafunded.png',
  32: '/logos/phoenixtrader.png',
  34: '/logos/uprofit.png',
  35: '/logos/thinkcapital.png',
  37: '/logos/breakoutprop.png',
  41: '/logos/maventrading.png',
  42: '/logos/cryptofundtrader.png',
  43: '/logos/bemfunding.png',
  44: '/logos/toponetrader.png',
  45: '/logos/qtfunded.png',
  46: '/logos/fortraders.png',
  47: '/logos/tradethepool.png',
  48: '/logos/fundedelite.png',
  49: '/logos/finotivefunding.png',
  50: '/logos/monetafunded.png',
  51: '/logos/atfunded.png',
  52: '/logos/hantectrader.png',
  53: '/logos/axiselect.png',
  54: '/logos/nordicfunder.png',
  55: '/logos/fundedtradingplus.png',
  56: '/logos/fintokei.png',
  57: '/logos/tradeify.png',
  58: '/logos/myfundedfutures.png',
  59: '/logos/alphafutures.png',
  60: '/logos/lucidtrading.png',
  61: '/logos/toponefutures.png',
  62: '/logos/fundednextfutures.png',
  63: '/logos/traderslaunch.png',
  64: '/logos/aquafutures.png',
  65: '/logos/blueberryfutures.png',
  66: '/logos/e8futures.png',
  67: '/logos/futureselite.png',
  68: '/logos/goatfundedfutures.png',
  69: '/logos/yrmprop.png',
  70: '/logos/sharkfunded.png',
  71: '/logos/sfxfunded.png',
  72: '/logos/fundedsquad.png',
  73: '/logos/ftuk.png',
  74: '/logos/propshoptrader.png',
  75: '/logos/fundedfirm.png',
};

const localLogosByName: Record<string, string> = {
  'FTMO': '/logos/ftmo.png',
  'The 5%ers': '/logos/the5ers.png',
  'Funded Next': '/logos/fundednext.png',
  'Apex Trader': '/logos/apex.png',
  'TopStep': '/logos/topstep.png',
  'Funder Pro': '/logos/funderpro.png',
  'True Forex': '/logos/trueforex.png',
  'Earn2Trade': '/logos/earn2trade.png',
  'Instant Funding': '/logos/instantfunding.png',
  'FundingPips': '/logos/fundingpips.png',
  'Alpha Capital': '/logos/alphacapital.png',
  'Blue Guardian': '/logos/blueguardian.png',
  'E8 Markets': '/logos/e8funding.png',
  'FXIFY': '/logos/fxify.png',
  'Lark Funding': '/logos/larkfunding.png',
  'The Trading Pit': '/logos/thetradingpit.png',
  'GoatFunded Trader': '/logos/goatfunded.png',
  'City Traders Imperium': '/logos/citytradersmperium.png',
  'Hola Prime': '/logos/holaprime.png',
  'Audacity Capital': '/logos/audacitycapital.png',
  'OneUp Trader': '/logos/oneuptrader.png',
  'Bulenox': '/logos/bulenox.png',
  'Take Profit Trader': '/logos/takeprofittrader.png',
  'TradeDay': '/logos/tradeday.png',
  'My Flash Funding': '/logos/myflashfunding.png',
  'AquaFunded': '/logos/aquafunded.png',
  'Phoenix Trader': '/logos/phoenixtrader.png',
  'Uprofit': '/logos/uprofit.png',
  'ThinkCapital': '/logos/thinkcapital.png',
  'Breakout Prop': '/logos/breakoutprop.png',
  'Blueberry Funded': '/logos/blueguardian.png',
  'Top One Futures': '/logos/topone.png',
  'Maven Trading': '/logos/maventrading.png',
  'Crypto Fund Trader': '/logos/cryptofundtrader.png',
  'BEM Funding': '/logos/bemfunding.png',
  'Top One Trader': '/logos/toponetrader.png',
  'QT Funded': '/logos/qtfunded.png',
  'For Traders': '/logos/fortraders.png',
  'Trade The Pool': '/logos/tradethepool.png',
  'FundedElite': '/logos/fundedelite.png',
  'Finotive Funding': '/logos/finotivefunding.png',
  'Moneta Funded': '/logos/monetafunded.png',
  'ATFunded': '/logos/atfunded.png',
  'Hantec Trader': '/logos/hantectrader.png',
  'Axi Select': '/logos/axiselect.png',
  'Nordic Funder': '/logos/nordicfunder.png',
  'Funded Trading Plus': '/logos/fundedtradingplus.png',
  'Fintokei': '/logos/fintokei.png',
  'Tradeify': '/logos/tradeify.png',
  'My Funded Futures': '/logos/myfundedfutures.png',
  'Alpha Futures': '/logos/alphafutures.png',
  'Lucid Trading': '/logos/lucidtrading.png',
  'FundedNext Futures': '/logos/fundednextfutures.png',
  'Traders Launch': '/logos/traderslaunch.png',
  'AquaFutures': '/logos/aquafutures.png',
  'Blueberry Futures': '/logos/blueberryfutures.png',
  'E8 Futures': '/logos/e8futures.png',
  'FuturesElite': '/logos/futureselite.png',
  'Goat Funded Futures': '/logos/goatfundedfutures.png',
  'YRM Prop': '/logos/yrmprop.png',
  'SharkFunded': '/logos/sharkfunded.png',
  'SFX Funded': '/logos/sfxfunded.png',
  'FundedSquad': '/logos/fundedsquad.png',
  'FTUK': '/logos/ftuk.png',
  'PropShopTrader': '/logos/propshoptrader.png',
  'FundedFirm': '/logos/fundedfirm.png',
};

interface FirmLogoProps {
  domain?: string;
  name: string;
  abbr: string;
  color: string;
  size?: number;
  radius?: number;
  style?: React.CSSProperties;
  className?: string;
  firmId?: number;
}

export function FirmLogo({ domain, name, abbr, color, size = 40, radius = 10, style = {}, className = '', firmId }: FirmLogoProps) {
  const localSrc = firmId ? localLogos[firmId] : localLogosByName[name];
  const [src, setSrc] = useState<string | null>(localSrc || null);
  const fontSize = Math.max(9, Math.floor(size * 0.26));

  return (
    <div
      className={`firm-logo-wrap ${src ? 'firm-logo-glow' : ''} ${className}`}
      style={{
        width: size, height: size, borderRadius: radius,
        background: src ? '#0c1420' : color,
        overflow: 'hidden', flexShrink: 0,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        border: '1px solid rgba(255,255,255,0.15)',
        ...style,
      }}
    >
      {src ? (
        <img
          src={src}
          alt={name}
          style={{ width: '82%', height: '82%', objectFit: 'contain', display: 'block', filter: 'brightness(1.15) contrast(1.05)' }}
          onError={() => setSrc(null)}
        />
      ) : (
        <span style={{
          fontFamily: "'Space Grotesk', sans-serif", fontWeight: 900,
          color: '#fff', fontSize, lineHeight: 1, textAlign: 'center',
          padding: '0 2px', userSelect: 'none', background: color,
          width: '100%', height: '100%', display: 'flex',
          alignItems: 'center', justifyContent: 'center',
        }}>
          {abbr}
        </span>
      )}
    </div>
  );
}
